### ISSUE TITLE
This repo needs a maintainer

### ISSUE THREAD

**Issue by cgreening** [cgreening/grunt-liquibase#16]
I haven't used liquibase or grunt for some time. Would someone like to take over this project and npm package?

**Comment by ecasilla** [comment]
I still use this package I can take it over

**Comment by cgreening** [comment]
If you let me know your npmjs username I can add you as a maintainer of the package.

**Comment by cgreening** [comment]
I'm also happy to transfer the ownership of the repo over to your account - that way you can manage it going forward.

**Comment by ecasilla** [comment]
npm username ecasilla

**Comment by ecasilla** [comment]
sure you can transfer it over thanks!

**Comment by cgreening** [comment]
Done!
