### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by sameetn** [cgreening/grunt-liquibase#4]
Hi,

Not sure if you are still maintaining this, but suddenly today I started getting this error 

```npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\WS\\tools\\nodejs4.2.2\\node.exe" "C:\\WS\\tools\\nodejs4.2.2\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for ....\registry.npmjs.org\grunt-liquibase\-\grunt-liquibase-0.1.5.tgz
npm ERR! Expected: 68286b00be626e6cf2b05aa3c51fcde7b411be4d
npm ERR! Actual:   402dad47e54a7b8e43e337560e2aae3bf51ea34e
npm ERR! From:     http://registry.npmjs.org/grunt-liquibase/-/grunt-liquibase-0.1.5.tgz
npm ERR!
```
I tried changing the version of node to 5, cleaning my cache, removing all traces of grunt-liquibase from my local and I still get this. There seems to be some issue.

**Comment by cgreening** [comment]
I've just pushed a new version up to npm 0.1.6 - can you try again?

**Comment by sameetn** [comment]
works now. We moved to using an internal npm registry so it seems fine.
